spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/ec-202001d
      username: postgres
      password: postgres
    
  mail:
   username: namiki.ba13@gmail.com
   password: afuyrdkpltnyqdyh
   host: smtp.gmail.com
   port: 587
   properties:
     mail.smtp.auth: true
     mail.smtp.starttls.enable: true